### ISSUE TITLE
CPAN release contains obsolete "Makefile"

### ISSUE THREAD

**Issue by fschlich** [lestrrat-p5/XML-RSS-LibXML#4]
The CPAN release of XML-RSS-LibXML 0.3103 contains the file "Makefile" in both tarball and MANIFEST, which I believe is a leftover and does not belong there. CPAN testers don't seem to mind, but its existence confuses the Debian package build process (it takes precedence over Build.PL, but it's default target has a dependency on Makefile.PL, which doesn't exist...)

**Comment by lestrrat** [comment]
https://metacpan.org/release/DMAKI/XML-RSS-LibXML-0.3104

Done. Thanks for the report!
