### ISSUE TITLE
Test failures with perl 5.18.x and 5.19.x

### ISSUE THREAD

**Issue by eserte** [lestrrat-p5/XML-RSS-LibXML#5]
http://matrix.cpantesters.org/?dist=XML-RSS-LibXML%200.3104 shows test failures just for the perl versions 5.18.x and 5.19.x. I did not look further into the issue. An idea could be the new hash randomization code in perl.

**Comment by lestrrat** [comment]
sounds very likely... it doesn't look like there's an explicit dependency on order, but it might have just been working by coincidence. looking at it, but am not sure exactly what the cause just yet.

**Comment by lestrrat** [comment]
@eserte for some reason this fixed it for me. can you confirm? e98a639f1ff9f9ae4a5477268e5c2d88f68640f1

**Comment by eserte** [comment]
Yes, I can confirm. No problem with perl 5.19.11 on a FreeBSD 9.2 system after executing the test suite five times.
